### ISSUE TITLE
Publish to pypi on tagged commits

### ISSUE THREAD

**Issue by bahlo** [axiomhq/axiom-py#5]

**Comment by flore2003** [comment]
Can we get a pre-release published on pypi? That would make it much easier to include this in our CI pipeline

**Comment by bahlo** [comment]
Yes, will put something up today! Just a heads up: The state right now is that we do one http request per event which is pretty inefficient (see #4), we hope to get that fixed next week.

**Comment by bahlo** [comment]
https://pypi.org/project/axiom-py/
