### ISSUE TITLE
Documentation - add documentation on how to use the client.logger

### ISSUE THREAD

**Issue by drorIvry** [axiomhq/axiom-py#87]
Hi, 
I'm trying to use this package as a logger to send application logs to axiom, I saw there a bunch of code (like axiom.Logger etc...) but I couldn't figure out how to use it to send logs to an Axiom dataset. 
Can you please add documentation for this use case?

thanks!

**Comment by bahlo** [comment]
Hi @drorIvry, sorry to get back so late. You're right! Adding that in #123.
